#include "config.h"
#include "sta_ws_page.h"

static const char s_httpPage[] =
	"<!doctype html><html><head><meta charset='utf-8'>"
	"<meta name='viewport' content='width=device-width,initial-scale=1'>"
	"<title>OpenDoor STA</title>"
	"<style>"
	"*{box-sizing:border-box;}"
	"body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:12px;}"
	".card{width:min(520px,100%);background:#fff;border-radius:16px;padding:18px;box-shadow:0 10px 30px rgba(0,0,0,.08);}"
	"h2{margin:0 0 14px 0;font-size:22px;}"
	".row{display:flex;align-items:center;gap:10px;margin:10px 0;padding:10px 12px;background:#f9fafb;border-radius:12px;}"
	".switch{position:relative;display:inline-block;width:52px;height:30px;}"
	".switch input{opacity:0;width:0;height:0;}"
	".slider{position:absolute;cursor:pointer;inset:0;background:#ccc;transition:.2s;border-radius:30px;}"
	".slider:before{position:absolute;content:'';height:24px;width:24px;left:3px;top:3px;background:white;transition:.2s;border-radius:50%;}"
	"input:checked + .slider{background:#34c759;}"
	"input:checked + .slider:before{transform:translateX(22px);}"
	".state{font-weight:600;min-width:72px;}"
	".otaRow{display:flex;gap:8px;margin:10px 0;}"
	"#ota{flex:1;padding:10px 12px;border:1px solid #d1d5db;border-radius:10px;font-size:14px;}"
	"button{border:none;background:#2563eb;color:#fff;border-radius:10px;padding:10px 14px;font-size:14px;cursor:pointer;}"
	"button:hover{background:#1d4ed8;}"
	"#otaText{margin-top:8px;padding:10px 12px;background:#eef2ff;border-radius:10px;color:#1e3a8a;}"
	"#status{margin-top:10px;padding:10px 12px;background:#111827;color:#d1d5db;border-radius:10px;max-height:220px;overflow:auto;font-size:12px;}"
	"</style></head><body>"
	"<div class='card'>"
	"<h2>OpenDoor Control</h2>"
	"<div class='row'>"
	"<span class='state' id='doorState'>门已关闭</span>"
	"<label class='switch'>"
	"<input id='doorToggle' type='checkbox' onchange='toggleDoor(this.checked)'>"
	"<span class='slider'></span>"
	"</label>"
	"</div>"
	"<div class='otaRow'><input id='ota' value='" APP_OTA_DEFAULT_URL "' placeholder='http://host/app.bin'><button onclick=\"upgradeOta()\">升级</button></div>"
	"<div>"
	"<div id='otaText'>OTA: idle</div>"
	"<div id='deviceTime' style='margin-top:6px;color:#374151'>设备时间: --</div>"
	"</div>"
	"<pre id='status'>connecting...</pre>"
	"<script>"
	"let ws;"
	"let ignoreToggleEvent=false;"
	"let pollTimer=null;"
	"function setDoorView(isOpen){"
	"ignoreToggleEvent=true;"
	"const t=document.getElementById('doorToggle');"
	"t.checked=!!isOpen;"
	"document.getElementById('doorState').textContent=isOpen?'门已打开':'门已关闭';"
	"setTimeout(()=>{ignoreToggleEvent=false;},0);"
	"}"
	"function render(data){"
	"document.getElementById('status').textContent=JSON.stringify(data,null,2);"
	"if(data&&data.door&&typeof data.door.doorOpen==='boolean'){setDoorView(data.door.doorOpen);}"
	"if(data&&data.time){"
	"let ts=(typeof data.time.unix==='number')?data.time.unix:0;"
	"let iso=(typeof data.time.iso==='string')?data.time.iso:'--';"
	"document.getElementById('deviceTime').textContent='设备时间: '+iso+' (unix='+ts+')';"
	"}"
	"if(data&&data.ota){"
	"let w=(typeof data.ota.written==='number')?data.ota.written:0;"
	"let t=(typeof data.ota.total==='number')?data.ota.total:-1;"
	"let s=(typeof data.ota.speedBps==='number')?data.ota.speedBps:0;"
	"let text='OTA: state='+data.ota.state+' written='+w+'B';"
	"if(t>=0){text+=' total='+t+'B';}"
	"text+=' speed='+s+'B/s';"
	"document.getElementById('otaText').textContent=text;"
	"}"
	"}"
	"function connect(){"
	"ws=new WebSocket('ws://'+location.host+'/ws');"
	"ws.onopen=()=>ws.send('status');"
	"ws.onmessage=(e)=>{try{render(JSON.parse(e.data));}catch(_){document.getElementById('status').textContent=e.data;}};"
	"ws.onclose=()=>{if(pollTimer){clearInterval(pollTimer);pollTimer=null;}setTimeout(connect,1000);};"
	"if(!pollTimer){pollTimer=setInterval(()=>{if(ws&&ws.readyState===1){ws.send('status');}},1000);}"
	"}"
	"function toggleDoor(checked){"
	"if(ignoreToggleEvent){return;}"
	"if(ws&&ws.readyState===1){ws.send(checked?'open':'close');}"
	"}"
	"function upgradeOta(){if(ws&&ws.readyState===1){ws.send('ota_upgrade:'+document.getElementById('ota').value);}}"
	"connect();"
	"</script></div></body></html>";

const char *sta_ws_page_html_get(void)
{
	return s_httpPage;
}
